# SITE CONFIGURATION
title: ICCC 2020  # your site title
author: replace # You :P
description: > # Meta description of Homepage
  International Conference on Control, Communication and Computing, 2020
baseurl: "/ICCCC2020" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Dates', link: '/dates'}
  - {name: 'Events', link: '/events'}
  - {name: 'Organizers', link: '/organizers'}
  - {name: 'Call for Papers', link: '/cfp'}
  #- {name: 'Gods Own Country', link: '/kerala'}
  

tagline: >
  International Conference on Control, Communication and Computing

hero_img: hero1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: iccc2020@cet.ac.in # email for form submission


disqus:
  shortname: replace # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  cards:
    output: true


# sass:
#     sass_dir: _sass
